### ISSUE TITLE
Date and Time input shows dates as browser timezone instead of dashboard timezone

### ISSUE THREAD

**Issue by LarsStegman** [VolkovLabs/business-forms#308]
Hi,

I am not sure whether this is a bug or an intentional design decision. A date and time input fields shows its values as in the browser local time zone, but as we are an international company, we have most of our dashboards set to use UTC time. The users needing to enter the time in their local time zone, while all other times on the dashboard are shown as UTC is confusing. Could you add a feature to specify whether a field should follow the dashboard timezone or the users' local time zones?

**Comment by mikhail-vl** [comment]
@LarsStegman Thank you for the feature request. We will look into adding it in the future release.

**Comment by asimonok** [comment]
Created an issue to Grafana to include support timezones - https://github.com/grafana/grafana/issues/80529
