### ISSUE TITLE
Is it possible to add custom buttons to the panel?

### ISSUE THREAD

**Issue by gdemin** [VolkovLabs/business-forms#457]
I want to make the following workflow with Business form panel:

1. User inserts some text in the text area.
2. User presses the button 'Prepare'.
3. I make some pure JS processing of the input and update a second text area with the results of processing.
4. Users can make editions of  the intermediate result if needed in the second text area.
5. User presses the 'Submit' button and I make the final processing.  

All works fine except that I don't know how to add the button 'Prepare'. I can emulate this behavior with the select box where the user chooses the action of the submit button, but  it is not user friendly.

So the question in the title: can we add the custom buttons to the form?

**Comment by mikhail-vl** [comment]
@gdemin Thank you for opening Feature Request.

  We will add button form element in the upcoming release.
