### ISSUE TITLE
Cannot read properties of undefined (reading 'payload') in Scenes dashboards

### ISSUE THREAD

**Issue by mikhail-vl** [VolkovLabs/business-forms#466]
Reported on Grafana v11.2.0-74515 (b4126d3bce) and `main` branch with `GF_FEATURE_TOGGLES_ENABLE=dashboardScene` enabled when adding a new panel.
In non-Scenes dashboards works as expected.

```
TypeError: Cannot read properties of undefined (reading 'payload')
    at o.onPanelMigration (migration.ts:203:30)
    at bd._pluginLoaded (VizPanel.js:241:36)
    at bd._loadPlugin (VizPanel.js:206:14)
    at async bd.changePluginType (VizPanel.js:280:5)
```

Is it breaking change recently introduced?

**Comment by asimonok** [comment]
Related issue - https://github.com/grafana/grafana/issues/92000
