### ISSUE TITLE
Business Forms plugin not working in Grafana Cloud

### ISSUE THREAD

**Issue by paulfirstimpression** [VolkovLabs/business-forms#467]
### Context
We are planning to move to Grafana Cloud (currently we host our own instances of Grafana).
Since disable_sanitize_html is not possible in Granafa Cloud, running javascript in a Text visualisation is not possible.

We discovered Business Forms, it looks great to do the job.
For testing, we set up a Grafana Cloud Free instance.

### Issue / reproduction
I installed the Business Forms plugin through the Grafana plugins panel.
Ater a few minutes, the plugin appears as installed. 
Next, when I edit a Grafana panel and select Business Forms as a Visualisation. the Edit Panel fields are not changed to those of the Business Forms, but stay the same as the last selected visualisation. (for example, if the visualisation was Text Visualisation and I change it to Business Forms, I keep seeing the fields of the Text Visualisation).

### Environment
Currently Grafana Cloud latest is v11.2.0-74515.
Browsers: Chrome Version 127.0.6533.120 (Official build) (64-bits) / Edge Version 127.0.2651.105 (Official build) (64-bit)

On a self hosted Grafana v11.1.4 (2355de00c6) Enterprise Free instance on Ubuntu  20.04.6 LTS,  Business Forms works as expected.

**Comment by mikhail-vl** [comment]
@paulfirstimpression Thank you for reporting the issue. It's a breaking change in the Grafana Cloud introduced recently.

Related issue - https://github.com/grafana/grafana/issues/92000

**Comment by mikhail-vl** [comment]
@paulfirstimpression Plugin was updated in Grafana Cloud and works as expected.

https://grafana.com/grafana/plugins/volkovlabs-form-panel/

**Comment by paulfirstimpression** [comment]
@mikhail-vl great work! Thanks for the quick response!
