### ISSUE TITLE
Issue with Volkov Labs Echarts Panel Plugin After Upgrading to Grafana 11.1.0

### ISSUE THREAD

**Issue by ArtursTrubacs** [VolkovLabs/business-forms#471]
I recently upgraded my Grafana instance from version 10.0.2 to 11.1.0. I have been using the Volkov Labs Echarts Panel plugin installed via Dockerfile (volkovlabs-echarts-panel) with Apache Echarts without any issues in the older Grafana version. However, after the upgrade, the plugin now appears under the name Business Charts in Grafana, and chart not works, chart what i use is Sankey chart.
I understand that the volkovlabs-echarts-panel plugin might now be referred to as Business Charts, but this change has caused some confusion, and I am experiencing errors when trying to use my existing dashboards that previously worked without any problems.

What steps can I take to resolve the errors and ensure my dashboards using this plugin function correctly after the upgrade?
I appreciate your help in resolving this issue, as this plugin is crucial for my Grafana setup.

Error output 

ECharts Execution Error
data is not defined
`
ReferenceError: data is not defined
    at eval (eval at <anonymous> (https://name-of-grafana-instance/public/plugins/volkovlabs-echarts-panel/module.js?_cache=6.2.0:175:4689), <anonymous>:7:1)
    at https://name-of-grafana-instance/public/plugins/volkovlabs-echarts-panel/module.js?_cache=6.2.0:175:6740
    at Ud (https://name-of-grafana-instance/public/build/1247.34022e0fa8ad25da7b32.js:953:26125)
    at nl (https://name-of-grafana-instance/public/build/1247.34022e0fa8ad25da7b32.js:953:45489)
    at https://name-of-grafana-instance/public/build/1247.34022e0fa8ad25da7b32.js:953:43678
    at O (https://name-of-grafana-instance/public/build/1247.34022e0fa8ad25da7b32.js:1036:1549)
    at MessagePort.J (https://name-of-grafana-instance/public/build/1247.34022e0fa8ad25da7b32.js:1036:1913)
`

**Comment by mikhail-vl** [comment]
@ArtursTrubacs Apache ECharts panel joined Business Suite for Grafana we are developing and was renamed to Business Suite. The same time, we implemented breaking changes in v6. Please refer to the migration guide in the blog: https://volkovlabs.io/blog/echarts-panel-6.0.0-20240406/#migration-guide

  We implemented migration logic in the panel, but it's not possible to cover all use cases.
  Please let us know if there is anything else.
