### ISSUE TITLE
Pre-Selection of "Multi select with custom options" options

### ISSUE THREAD

**Issue by bperun123** [VolkovLabs/business-forms#473]
Hey guys,

first of all: Big thanks for your amazing work!

One question:

How can I pre-select the options of a Multi Select (I also tried it with "Radio group with custom options" - also doesn't work for me). For single values like "name" or "status" (Input field) everything works fine to fetch these values initially from the DB. However for multi values it doesn't work for me atm. I also tried a few formats (see screenshot).

Maybe you have a hint for me how to achieve that. Thanks in advance!

![image](https://github.com/user-attachments/assets/2282f323-943d-4127-9c0d-a3cbbd580950)

**Comment by mikhail-vl** [comment]
@bperun123 Thank you for reporting. We identified the issue and will fix it in the upcoming release.
