### ISSUE TITLE
Multi-line issue with text areas

### ISSUE THREAD

**Issue by bperun123** [VolkovLabs/business-forms#475]
Thanks for your fast reply.

I think I found one more issue at text areas:
![image](https://github.com/user-attachments/assets/9612d9f4-3980-4d98-ba77-d9d9a730d2ab)

If I update a multiline statically, everything works fine:
![image](https://github.com/user-attachments/assets/38beb157-c6a3-48a0-8985-b912316396fc)

However, if I switch back to the payload of the text area, it breaks:
![image](https://github.com/user-attachments/assets/d4d8cd0b-2007-4a3a-9320-1369fed20d7a)

Maybe you can check on your side, if this is also an issue which should be fixed. 
I assume an issue at payload converting in terms of multi-line strings...

Thanks a lot :)

**Comment by vitPinchuk** [comment]
@bperun123 Thanks for the question.

We will add appropriate updates to the documentation. It is an interesting case. 

`Create Payload` code editor should contain the following logic:
1. Find element refer to TextArea
2. Add replace logic to value `payload[element.id] = element.value.replaceAll("\n", "\\n");`

here is example 

```js
const payload = {};

context.panel.elements.forEach((element) => {
  if (!element.value) {
    return;
  }

  /**
   * Required logic to update the value 
   */
  if (element.id === 'description2') {
    payload[element.id] = element.value.replaceAll("\n", "\\n");
    return;
  }

  payload[element.id] = element.value;
})


console.log('console >>> upd payload', payload)

/**
 * Data Source payload
 */
return payload;
```

![image](https://github.com/user-attachments/assets/a06b31f3-0dc9-49c0-b408-ad2081651531)

This allows the line break to be properly converted 

Here is my full example, please base it on it

![image](https://github.com/user-attachments/assets/eda23783-8d55-4ab7-9161-cf8ec130b787)

`Create payload`

![image](https://github.com/user-attachments/assets/215a7e14-7e36-4653-8e34-754722ff4a9f)


[Запись экрана от 28.08.2024 16:55:52.webm](https://github.com/user-attachments/assets/e60407a8-5e81-4b48-9851-2eef1f16b12b)

**Comment by mikhail-vl** [comment]
Documentation updated: https://volkovlabs.io/plugins/business-forms/data-flow/#use-text-area-with-multiple-lines
