### ISSUE TITLE
Grafana variable in panel

### ISSUE THREAD

**Issue by IHopeThisIsNotPermanent** [VolkovLabs/business-forms#478]
# The Issue
Grafana panels allow you to basically do string formatting with Grafana variables in most of their text fields. In all of the default fields in the business variable this works - though the fields which are associated with the specific behavior of this panel do not do this substitution. 

# Specifications

Grafana Version: v10.4.1

Business Variable Version: 3.0.0

# The Grafana variable

I'm just using a custom variable, which is a list of strings.

![pic1](https://github.com/user-attachments/assets/b40cc94f-d3ea-4d0a-852a-c8111c0ae48a)

# The code in the widget

These two work:

![code_1](https://github.com/user-attachments/assets/6dd3bea8-a3e1-4117-9abc-2dca0147156e)

These three do not work:

![code_2](https://github.com/user-attachments/assets/7cb11378-c117-4602-acc0-05f90a68793d)

These screenshots capture the working/not working behavior seen on the dashboard

![result_1](https://github.com/user-attachments/assets/fd285f9e-18ca-42e3-8ff2-d22fbf714e50)

![result_2](https://github.com/user-attachments/assets/122e2a1d-77ed-448d-ba9b-315a92b47a29)

**Comment by cgravita** [comment]
Good morning, I saw that the upgrade has already been applied. I wanted to ask, is there a plan to extend this functionality to module and section labels too?

Using the same nomenclature as the previous post, these screenshots capture the not working behavior seen on the dashboard

![Schermata del 2024-09-06 10-35-00](https://github.com/user-attachments/assets/2c305e50-0b4d-4fb3-83d5-7b6b6daa092b)

**Comment by mikhail-vl** [comment]
@cgravita Thank you for suggestion, we will implement in the upcoming release.
