### ISSUE TITLE
Initial values for elements

### ISSUE THREAD

**Issue by Vovaman** [VolkovLabs/business-forms#486]
![01](https://github.com/user-attachments/assets/710db04f-1e7a-467d-8e03-4f56876f8166)
1) Panel is BusinessForms
2) Add my elements
3) Initial request returns data

![02](https://github.com/user-attachments/assets/a519b1d0-6e0f-45c8-a7e9-b98c822cec5d)
1) Initial request well-defined (...confirmed by previous picture) and aliases are assigned.
2) Field names are filled.

Result: form is empty.
![03](https://github.com/user-attachments/assets/4c9a1215-9e63-4947-8c1c-26fdc8e6588a)

What's wrong?

**Comment by Vovaman** [comment]
Grafanf: docker image ``grafana/grafana-enterprise:10.4.4``
BusinessForms: 
![Screenshot_20240906_212027](https://github.com/user-attachments/assets/1ca8d1b2-9e09-497f-b021-c920f728f851)
Data source - JSON API:
![Screenshot_20240906_212144](https://github.com/user-attachments/assets/157b0e14-2129-4041-8bc8-6605cf5413b8)

**Comment by mikhail-vl** [comment]
@Vovaman Have you tried to use Query for Initial request instead of Data Source?

  Using Query you can check returned data in the `Table View` to make sure that you receive it from the data source.
  You don't need to use Data Source directly in the Initial Request if you don't create specific payload.

**Comment by Vovaman** [comment]
1) Yes, if I use Query, data appear.
2) But I plan to construct some complex payload and this is why DataSource is preferrable.
3) It seems this block doesn't work anyway, because I don't see any attempt to make request in browser log
![image](https://github.com/user-attachments/assets/a8e8a688-176f-48cc-9ad9-c16c9d65d4f7)
4) It would be great to get opportunity to use part of ${payload} in ``Path`` tab:
![image](https://github.com/user-attachments/assets/0a9cf845-5fea-448e-bffe-b315684fc1b4)

**Comment by mikhail-vl** [comment]
@vitPinchuk Could you please investigate.
