### ISSUE TITLE
Updating a Grafana variable using context.grafana.locationService.partial also triggers/resets the current panel string input

### ISSUE THREAD

**Issue by paulfirstimpression** [VolkovLabs/business-forms#489]
Hi there,

First of all, you're doing great work building all the tools! 
Unfortunately, I've been stuck for a few days trying to build a dashboard that updates a Grafana variable (service_call) after changing a string input in a Business Form. Hope you can help or give a hint.

These are the steps I follow:
1. Populate Grafana variable ${DeviceID}
2. ${DeviceID} triggers an update of Grafana variable ${service_call} AND
3. 
    a. ${DeviceID} triggers an update of the Business Form
    b. ${service_call} triggers an update of a SAP details panel

4. Changing the "string input" Service Call should change the Grafana variable ${service_call} using LocationService.partial and trigger an update of the SAP details panel. This seems to work, the Grafana var service_call is changed, so is the SAP details panel that uses this var.

But:

5. Unexpected: The Business form also sets back the Service Call string input to its original value.
- The Business form or its source does not use the ${service_call} variable.
- The Business form does not seem to trigger a source refresh (good behaviour, as expected), since the Status update ($now() field) does not change.
- It does not matter if the Service Call field has focus or not (I tried a setTimeout for LocationService.partial to select and focus another field)

I tried to follow [this example:](https://volkovlabs.io/plugins/business-forms/variables/), but in my case, the "string input" form element does not have a source option.

My initial request is done using a JSON Source query, after which initial fields are set by query fields.
The ${service_call} variable is never used in the Business Form as a query variable (only in locationService.partial to set it). 

Thanks in advance and best regards,
Paul Notebaart

Below my schematic work flow:

![business forms var change 01](https://github.com/user-attachments/assets/1ed8aca7-a783-4923-b07e-2187615bf3f6)

![business forms var change 02](https://github.com/user-attachments/assets/cc34041c-1bbb-47b8-94b5-fc7de277dbd8)

**Comment by vitPinchuk** [comment]
@paulfirstimpression Thank you for your question.

The form allows you to manage data to the panel or in reverse order

Controlling and working with variables through code doesn't go quite right when there is synchronization with the dashboard.

When using `locationService.partial` and `Synchronize with data` is enabled, it will cause the panel to refresh every time and run an initial request when `locationService.partial` called.

In your case option  `Synchronize with data` is enabled, to allow you to set initial values depending on the selected device.


1) You can disable the `Synchronize with data` option.
2) If you do not want to set initial values for only one item, `Service Call`, you can cancel the initial value setting for this field. This will allow you to set initial values for items other than the `Service Call` item.

**Comment by paulfirstimpression** [comment]
@vitPinchuk thanks for your help and clear answer. 
Good to know that `locationService.partial` in that case always triggers a panel refresh (instead of only updating the var, which triggers a refresh of panels depending on the var).

I will try and play with option 2, using `Synchronize with data` enabled, linking all fields except for `Service Call`.
And then set `Service Call` by intial custom code, only if `DeviceID` has changed (if I can find a way to store the previous `DeviceID`).
