### ISSUE TITLE
Form element ready-only query mode without values

### ISSUE THREAD

**Issue by GuiRochaSawluz** [VolkovLabs/business-forms#493]
Hello, good evening, I'm having a problem inserting the value in a query using the element as Ready-only
![image](https://github.com/user-attachments/assets/a6f0548d-f44f-4c7f-babc-5aec6c76516e)

**Comment by vitPinchuk** [comment]
@GuiRochaSawluz Thank you for question

Please, to set initial values to read-only element use `Initial Fields` -> `Query Fields` option below `Initial Request` option section

![image](https://github.com/user-attachments/assets/a93a3525-0587-452a-8688-7086c4d48a2d)
