### ISSUE TITLE
Some good examples or simple guide required for API usage

### ISSUE THREAD

**Issue by vanimesh** [VolkovLabs/business-forms#494]
Hi Team,

We have been using the plugin since some time, but we are always struck in some places and we were looking for some documentation. Is it possible if you can add some good examples in the documentation on how to use the REST API procedures ?

- How actually the plugin sends the the values form elements? For all the methods if applciable etc.
Thank you very much.

**Comment by mikhail-vl** [comment]
@vanimesh Business Forms has various REST API examples in documentation: https://volkovlabs.io/plugins/business-forms/servers/

  In the latest version of Business Forms we added Query editors for data sources and recommend to use data source for REST API as explained in the blog post: https://volkovlabs.io/blog/infinity-data-source-2024720/

**Comment by vanimesh** [comment]
Hi @mikhail-vl , I am using the api from django hope that won't be any issue and also it's not covered here https://volkovlabs.io/plugins/business-forms/servers/

And we are still using the older version of the plugin hope the steps in the url excluding the infinity data source works? 

Also another question how would I pass the form elements into the url? And can I add any validations for say the form elements should contain only numbers from some range

**Comment by vanimesh** [comment]
Hi @vitPinchuk , i had gone through the documentation but i couldnt find any place where i can find the query editor(https://volkovlabs.io/blog/infinity-data-source-2024720/#query-editor) , can you please help ?

**Comment by vitPinchuk** [comment]
@vanimesh 

Query Editor  is available in `Update Request` option section. When selecting a data source from the list below `Custom Code` you have the `Update Request Payload` section and `Query Editor` will be presented in it.

![image](https://github.com/user-attachments/assets/d13e113b-11c5-44d3-9af6-8fc2182806ed)

In a neighboring issue, you mentioned that you have already updated the plugin to version 4.5 

Is your initial question (Some good examples or simple guide required for API usage ) still valid?

**Comment by vanimesh** [comment]
Yes @vitPinchuk the question "Is your initial question (Some good examples or simple guide required for API usage ) still valid?" is still valid :-).
Also the question "Also another question how would I pass the form elements into the url? And can I add any validations for say the form elements should contain only numbers from some range"

And the infinity data source mentioned above(infinity) is mandatory for the options to appear ?

**Comment by vitPinchuk** [comment]
@vanimesh infinity was specified for the example, `query-editor` depends on the data source

[query-editor](https://volkovlabs.io/plugins/business-forms/data-flow/#query-editor-and-frontend-data-source)

**Comment by mikhail-vl** [comment]
@vanimesh If you use API directly, then it's enough.
