### ISSUE TITLE
Getting the error Request ReferenceError: data is not defined after plugin upgrade to 4.5 from 3.7

### ISSUE THREAD

**Issue by vanimesh** [VolkovLabs/business-forms#495]
Hi Team,

I am getting the error "Request ReferenceError: data is not defined" after upgrading the plugin to 4.5. I am using the element of type file

**Comment by vanimesh** [comment]
Please do let me know if any further details required

**Comment by vanimesh** [comment]
![image](https://github.com/user-attachments/assets/d52a3208-8b15-4745-9a34-0fe544fa588a)

**Comment by vitPinchuk** [comment]
@vanimesh Thank you for your question

In version 4.0.0 were Breaking changes bounded with non-context code parameters. 

[4.0.0 (2024-07-01)](https://volkovlabs.io/plugins/business-forms/release/#400-2024-07-01)  

`data -> context.panel.data`  

Please see the non-context code and update it to use the context 

If that doesn't help, provide your JSON dashboards, please. 
Thanks

**Comment by mikhail-vl** [comment]
Updated parameters also described in the documentation: https://volkovlabs.io/plugins/business-forms/code/

We have migration logic from previous versions to Business Forms, but it's impossible to cover all use cases and some times you can see undefined errors, which should be updated manually.
