### ISSUE TITLE
Azure Managed Grafana Integration

### ISSUE THREAD

**Issue by kvecc** [VolkovLabs/business-forms#496]
Hi Team,

I am trying to use the Business-Forms panel on Azure Managed Grafana, but it will only install version 3.6 of the panel plugin. Doing some research, it seems Azure picks the version based on different compatibility, stability, and security concerns. I was wondering if there is a timeline on when versions >= 4.1 will be available on Azure Managed Grafana, or if there is different way I can install specific versions of the panel.

In general, I'm having issues sending data back to my MSSQL server, and it seems like using version >=4.1 would help greatly with properly formatting the Update payload code.

**Comment by mikhail-vl** [comment]
@kvecc You are correct, version 4.1 has query editor for data sources, which help with payload and improves user experience.

  Our Business Suite plugins are registered in the Grafana Catalog, but I am not familiar with the process of updating plugins in the Azure Managed service. Most probably, it's done using support requests.

  Can you check with the Azure support? I am checking with Grafana team as well.

**Comment by kvecc** [comment]
@mikhail-vl Thanks for the response, I will submit a ticket with Azure support to try and get more information

**Comment by mikhail-vl** [comment]
@kvecc I am waiting for the response from Grafana team who is talking to Azure team.

  Let me know if your heard anything from support.

**Comment by kvecc** [comment]
@mikhail-vl I received one email from Azure support in which they were trying to clarify my issue, but they also said since Azure Managed Grafana is a 3rd party resource they can only really help with issues relating to the resource failing to deploy and issues with data not populating

**Comment by mikhail-vl** [comment]
@kvecc Ok, I will let you know when hear back from Grafana team.
