### ISSUE TITLE
Multi select with custom input

### ISSUE THREAD

**Issue by The1hauntedX** [VolkovLabs/business-forms#503]
The multi select element should allow for custom input like https://developers.grafana.com/ui/canary/index.html?path=/story/forms-select--custom-value-creation&args=isMulti:!true

![image](https://github.com/user-attachments/assets/b9f6a8ab-d2d8-4f83-84c8-7a6c3e0036d3)

**Comment by mikhail-vl** [comment]
@The1hauntedX Thank you for raising the issue. Most probably, we will need to enable it with panel option.
