### ISSUE TITLE
Error Update on MySQL

### ISSUE THREAD

**Issue by arestahobby** [VolkovLabs/business-forms#509]
Hi teams pls help my case, value updated succesfully but nothing happen on my MySQL?
![test](https://github.com/user-attachments/assets/e148f2cd-5074-4480-af4a-d3d69e926bdd)
![test1](https://github.com/user-attachments/assets/a074ca86-bcb3-4ff1-bf8c-c9892e4be6ad)

**Comment by arestahobby** [comment]
![image](https://github.com/user-attachments/assets/4c14f1da-18b1-48e4-8e4c-da2bc2728365)
I Have modified query (add ' ') but still error, pls advice

**Comment by mikhail-vl** [comment]
@arestahobby `CostCenter` is a dashboard variable and should be used in the QueryEditor as `${CostCenter}`.
  Object `payload` includes only properties set in the Payload code.

**Comment by arestahobby** [comment]
Wow Great its works, can we use insert into on update query editor ?

**Comment by arestahobby** [comment]
Great tks, how to make reset button works (clear text previous) ?
![image](https://github.com/user-attachments/assets/68ae286a-7191-453f-9878-129d45dc9049)
