### ISSUE TITLE
Bug/irregularity: Form element [Read-only text area] does not act like a [read-only] element

### ISSUE THREAD

**Issue by paulfirstimpression** [VolkovLabs/business-forms#511]
A small bug/irregularity report about form element `[Read-only text area]`, that does not act like a `[read-only]` element
Grafana 11.2.2, Business Forms 4.6.0 

 **[Read-only text area]**
- Values color blue (or any Highlight Changes color) on data changes, not grey like a [read-only] element (after context.panel.patchFormValue);
```
  context.panel.patchFormValue({
    'Somefield1': '2024-10-04',
    'Somefield2': '12:00',
    'Description': 'Some text',
    'LastActivityNotes': 'Some other text'
  });
```
- On clicking submit, the Update Confirmation Window (with display values > Updated only) shows the [Read-only text area] values as changes.

```
      // ---Current quick fix:---
      let currentdata = context.panel.initial;  // First read the whole dataset, since there is no patchtInitial
      currentdata.Description = jsonpayload.Description;  // [Read-only text area 1]
      currentdata.LastActivityNotes = jsonpayload.LastActivity?.Notes;  // [Read-only text area 2]
      context.panel.setInitial(currentdata);
```

It would be nice if the `[Read-only text area]` would act like a `[read-only]` element.

Thanks!
Best regards, Paul

**Comment by mikhail-vl** [comment]
@paulfirstimpression Read-only elements are displayed using Read-only components, which prevent users to change them to compare initial and updated values. We don't restrict to change element's values using Code, which is use cases specific.

  If you need to modify read-only values and prevent them to color blue, you can use `context.panel.setInitial({})`: https://volkovlabs.io/plugins/business-forms/code/#parameters

  Will it work for you or you are looking for something else?

**Comment by paulfirstimpression** [comment]
@mikhail-vl that is the workaround I used now. 
But I see different behaviour between [Read-only text area] and [read-only] (one line string).

[read-only] greys out text as expected (dark grey) and does not show up in the submit dialog.

**Comment by mikhail-vl** [comment]
@vitPinchuk Could you please compare behavior between Read-Only and Read-only text area.
