### ISSUE TITLE
Refference Error Option Not defined on RESET

### ISSUE THREAD

**Issue by arestahobby** [VolkovLabs/business-forms#512]
Hi team pls help these issue
![image](https://github.com/user-attachments/assets/92bcc970-07dc-4779-9b59-be2fa561d42f)
here is my code : context.panel.onOptionsChange({
  ...options,
  elements: options.elements.map((element) => {
    if (["tanggal", "remark", "room"].includes(element.id)) {
      return { ...element, value: "" }; // Mengosongkan nilai elemen
    }
    return element;
  }),
});
![image](https://github.com/user-attachments/assets/428e0060-0ba4-40d2-870d-5b3fee749e82)

**Comment by mikhail-vl** [comment]
@arestahobby We updated documentation for the latest changes in Business Forms v4:

```
context.panel.onOptionsChange({
  ...context.panel.options,
  elements: context.panel.options.elements.map((element) => {
    return element.id === "name" ? { ...element, value: "test" } : element;
  }),
});
```
