### ISSUE TITLE
At Text area type, For update query, got error for Text input with line feed (press enter for next line)

### ISSUE THREAD

**Issue by KaungMAung** [VolkovLabs/business-forms#516]
At Text area type, For update request query, got error for Text input with line feed (press enter for next line)

**Comment by mikhail-vl** [comment]
@KaungMAung It's not clear what the issue is.

  Please provide version of Grafana, Business Forms, screenshots with error and how to reproduce to investigate.

**Comment by KaungMAung** [comment]
Config as below,
![image](https://github.com/user-attachments/assets/6c703947-b8eb-4333-97ba-a732229270ba)


At Text Area, using Enter key while entering data like below,
![image](https://github.com/user-attachments/assets/88b26248-36c4-47d9-8618-9219bdd839ee)

And submit data
![image](https://github.com/user-attachments/assets/a55c29db-9887-4493-af6d-c8497cc9a21e)

And error
![image](https://github.com/user-attachments/assets/88c93f94-d143-4896-85a5-f2ee9d38928d)

**Comment by KaungMAung** [comment]
Grafana Version : 11.2.2
Business Form Version : 4.7.0

**Comment by mikhail-vl** [comment]
@KaungMAung Please take at the https://github.com/VolkovLabs/business-forms/issues/475

  It also explained in the documentation: https://volkovlabs.io/plugins/business-forms/data-flow/#use-text-area-with-multiple-lines

**Comment by mikhail-vl** [comment]
@KaungMAung We discussed it with @vitPinchuk and will look into updating the plugin to fix it.

**Comment by KaungMAung** [comment]
Thank you so much, I will apply for a quick fix as in documentation for now.
