### ISSUE TITLE
Getting Request TypeError: Failed to fetch while sending POST Request to a URL. 

### ISSUE THREAD

**Issue by ashishagarwal7** [VolkovLabs/business-forms#519]
grafana version 9.5.20

Grafana dashboard is showing: Request TypeError: Failed to fetch, when submit button is clicked. Also, URL is receiving the POST request but data is not present inside that request. 
I am referring to this article to POST a form element data to a URL:
https://volkovlabs.io/blog/how-to-connect-the-data-manipulation-plugin-for-grafana-to-api-server-1abe5f60c904/#publicly-available-server

I don't know why I am getting this error also searched logs( /var/log/grafana) for error but no errors were there.

**Comment by mikhail-vl** [comment]
@ashishagarwal7 Check the Browser's console and network requests to troubleshoot the issue. You can see the payload and server response in the network activity. The references blog is pretty old and I would recommend to check the latest YouTube tutorials and documentation.

  If you are can upgrade to Grafana 10, we recommend to use the latest version of Business Forms panel with Infinity data source following blog: https://volkovlabs.io/blog/infinity-data-source-2024720/
