### ISSUE TITLE
Dynamic panel layout

### ISSUE THREAD

**Issue by cgravita** [VolkovLabs/business-forms#523]
Good evening! 
I've been diving deeper into how dynamic creation of form elements works in the Business Forms panel.

I think I’ve got a good grasp of the basics when it comes to creating and managing individual form elements. However, I believe it would be helpful to add a section to the forum that details the available keys and values for each element type. For example, listing all available "type" like "select," "slider," "boolean," "number," etc. I couldn’t find a dedicated section, so I’ve been experimenting on my own. If I wanted to create a "custom option radio group", what type should I enter? How do I decide the width of the Label? the color? the options? (this is an example, I don't need this information but a section that guides the user through all the available possibilities would be useful).

Along with this suggestion, I also wanted to ask if it's possible to manage the panel layout dynamically as well. Specifically, I'm looking to create sections dynamically, but I haven't found any guidance on how to do this.

Thank you!

**Comment by mikhail-vl** [comment]
@cgravita We have documentation for elements, which I am planning to update to make it more clear: https://volkovlabs.io/plugins/business-forms/form-elements/

  It's a good idea to provide JSON definition for dynamic elements. I will add it.
  You can't create sections dynamically, but it's a good idea and we will add it in future releases.
