### ISSUE TITLE
Sendind POST request(yes or no) from a grafana panel to an URL.

### ISSUE THREAD

**Issue by ashishagarwal7** [VolkovLabs/business-forms#526]
I am trying to send manual data yes or no to URL from grafana panel. But submit button is not working. I don't know why.

Referring the below link:

Data Manipulation Plugin for Grafana | Manual data entering and User input into Dashboard

https://www.youtube.com/watch?v=DXALVG8GijM

**Comment by mikhail-vl** [comment]
@ashishagarwal7 Submit button becomes active if any of the initial values were changed. It can also be updated manually using custom code.

  Please review documentation and our latest tutorials: https://volkovlabs.io/plugins/business-forms/code/
