### ISSUE TITLE
Initial fields for multi select - data format to save at DB

### ISSUE THREAD

**Issue by bperun123** [VolkovLabs/business-forms#531]
Which format do I have to use to save multiple values correctly at DB in order that it can be red by the "Initial fields" logic?

It seems to me that I either have to save the values as a string "2,3" or array {2,3} at my DB. However both doesn't work. It just shows the string term eg "2,3" at the multiple select checkbox.

![image](https://github.com/user-attachments/assets/721abe06-0540-4abc-aa6f-170841e3da84)

![image](https://github.com/user-attachments/assets/be6cb339-f066-4a41-82db-321e583a7117)

Can you give me a hint how to save multi selections correctly?!

**Comment by mikhail-vl** [comment]
@bperun123 Please try to use Transformation to transform string to a Grafana array, then it should work.

**Comment by bperun123** [comment]
@mikhail-vl Sry, I couldn't make it. Please, can you give me an example how to do that? I couldn't find a transformation which would be capable of doing this. I think you mean these transformations, right?
![image](https://github.com/user-attachments/assets/3af4c9a3-c9ad-4218-8e1a-ef8ac98d9c3f)

**Comment by bperun123** [comment]
@mikhail-vl After a longer search, I finally found a solution. 
Usual PostgreSQL arrays can be used to save these values at DB. Use pg function "unnest" to "translate" it. See:
![image](https://github.com/user-attachments/assets/9539c38c-7a6f-4b79-b0b8-3e9be6548228)

Maybe could be added to docs ;) 

Thx for your amazing work!

**Comment by bperun123** [comment]
@mikhail-vl Mh, this solution breaks if I have no values included at this field due to no DB rows are created (unnest just "splits" an empty array to 0 rows).

Maybe you have another idea how to fix that?!

![image](https://github.com/user-attachments/assets/f3547afb-0f86-4868-8142-6de073e98d6b)

**Comment by bperun123** [comment]
I think with that solution everything should work now. Tested it for empty, single selection, multi selection case.

I also share the part how I write the data into DB for others who encounter the same issues.
"used_by_workspace" is a postgresql INT array.

Hint: "Request Payload - All Elements" doesn't work for me due to the fact that the conversion wasn't unified. Eg it converts
"6" to an int, "1,3" as array "{1,3}". By converting it by code, everything is now a simple string with can be used at payload query editor between to brackets to indicate a PG array.

I don't know if this is best practise in terms of VolkovLabs, however it works for me now :)

![image](https://github.com/user-attachments/assets/b17b2886-f12c-44c8-a785-bdf09938fdb0)

**Comment by mikhail-vl** [comment]
@bperun123 Well done! I will update documentation.
