### ISSUE TITLE
[Question] ReplaceVariables not working? 

### ISSUE THREAD

**Issue by henjoe** [VolkovLabs/business-forms#533]
I want to automatically fill in my "Text Input" to be the current user in Grafana. 

On my element Value changed event I have the ff code: 

```
context.panel.elements.forEach(ele => {
  if (ele.id === 'name') {
    let currentUser = context.grafana.replaceVariables("${__user.login}");
    console.log('CurrentUser: ' + currentUser)
    ele.value = currentUser;
  }
})
```

but seems like the ```context.grafana.replaceVariables("${__user.login}")``` is not working. I received this error: 
![image](https://github.com/user-attachments/assets/7a67ab78-0992-4b26-b9c7-75d4ae461214)

What could be the temporary solutions for this kind of use case? 
Is there a way I can include the current login user in payload update request? 

Version: 3.8.0
Grafana: V9.2.2
OS: Windows

Thank you.

**Comment by henjoe** [comment]
Changing the code from here: 

```
 if (ele.id === 'name') {
    ele.value = "${__user.email}";
  }
```

Works fine.

**Comment by mikhail-vl** [comment]
@henjoe That's correct. Business Forms replaces dashboard variables automatically.
