### ISSUE TITLE
when you change the name of the datasource

### ISSUE THREAD

**Issue by DkCorpBo** [VolkovLabs/business-forms#536]
Hi, I just found a detail, when changing the name of the data source the forms stop working..

![image](https://github.com/user-attachments/assets/24bbae9f-a863-4a98-a6a2-3ab16fed4a58)

Looking at the JSON, I see that the name is there and not the id as it should be normally.

¿or maybe it is not possible?

**Comment by mikhail-vl** [comment]
@DkCorpBo Thank you for letting us know. We will look into it.
