### ISSUE TITLE
The enableSubmit and disableSubmit doesn't work as intended

### ISSUE THREAD

**Issue by dvdjda** [VolkovLabs/business-forms#545]
As per https://volkovlabs.io/blog/form-elements-validation-20240530/
the Submit button should stay disabled until all fields are enabled, but I test it and found that is not a case. Immediately after the first field (Facility) selected some value the Submit become available.

**Comment by mikhail-vl** [comment]
@dvdjda You need to select Manual enable update in the panel options to control it manually like discussed in the blog post.

![Screenshot 2024-11-07 at 9 12 00 AM](https://github.com/user-attachments/assets/862fd0c1-fcef-40c0-836f-c28953cbada2)

**Comment by dvdjda** [comment]
Thanks, its worked out as per you advise! 
Best regards!
