### ISSUE TITLE
This video article page is showing page not found. Do you have any alternative article for this video article. 

### ISSUE THREAD

**Issue by ashishagarwal7** [VolkovLabs/business-forms#548]
I was trying to send data on/off data to an URI referring the below video link:

"Data Manipulation Plugin for Grafana | Manual data entering and User input into Dashboard"
https://www.youtube.com/watch?v=DXALVG8GijM&t=429s

But not able to send data properly. Also the article present in this video is not opening.
Below image is showing on/off and submit button using which I am sending the data to a URL.

<img width="952" alt="image" src="https://github.com/user-attachments/assets/592b6d12-cbfe-49fa-9d7e-3e7dbbe07c97">

**Comment by mikhail-vl** [comment]
@ashishagarwal7 Thank you for letting us know. I updated the blog post link in the video: https://volkovlabs.io/blog/data-manipulation-panel-plugin-for-grafana-97f9af2c67e0/

  Please take a look at the latest blog post for Infinity data source and Business Forms which explains configuration: https://volkovlabs.io/blog/infinity-data-source-2024720/
