### ISSUE TITLE
Infinity DataSource Nested Object payload

### ISSUE THREAD

**Issue by asergeant01** [VolkovLabs/business-forms#549]
I am following [this blog post](https://volkovlabs.io/blog/infinity-data-source-2024720/#query-editor).

My Update Request "Create Payload" is basically:

```
var jsonData = {
  "createdBy": createdBy,
  "startsAt": startTime,
  "endsAt": endTime,
  "comment": comment,
  "matchers": matchers
}

return jsonData;
```

Whereby `matchers` is a further array of objects that is dynamically build based from form data.

My Query Editor "URL options" body content is the following:

```
{
  "createdBy": "${payload.createdBy}",
  "startsAt": "${payload.startsAt}",
  "endsAt": "${payload.endsAt}",
  "comment": "${payload.comment}",
  "matchers": ${payload.matchers}
}
```

This produces the following output on the request:
```
"executedQueryString": "###############
## URL
###############

https://<HIDDEN>

###############
## Curl Command
###############

curl -X 'POST' -d '{ 
\"createdBy\": \"alan\",
\"startsAt\": \"Thu Nov 14 2024 11:24:27 GMT+0000 (Greenwich Mean Time)\",
\"endsAt\": \"Sat Nov 16 2024 11:24:27 GMT+0000 (Greenwich Mean Time)\",
 \"comment\": \"Alan Test\",
\"matchers\": [object Object],[object Object],[object Object],[object Object]
}' -H 'Accept: application/json;q=0.9,text/plain' -H 'Authorization: Basic xxxxxxxx' -H 'Content-Type: application/json' 'https://<HIDDEN>'"
```

I would expect it to parse this or alternatively, provide the option to let the developer build the full body in "create payload" and return the `JSON.stringify` which can be inserted into the body content using `${payload}`

**Comment by mikhail-vl** [comment]
@asergeant01 Thank you for bringing it to our attention.

  We discussed it with the team and will look into improving objects in the upcoming release.

**Comment by asergeant01** [comment]
@mikhail-vl Awesome. Thanks. Until such times and for anyone else finding this, I was able to work around using the following:

```
var jsonData = {
  "createdBy": createdBy,
  "startsAt": startTime.toISOString(),
  "endsAt": endTime.toISOString(),
  "comment": comment,
  "matchers": JSON.stringify(matchers).replaceAll('\"', '\\"')
}
```

**Comment by mikhail-vl** [comment]
@asergeant01 Thank you for providing temporary solution.

**Comment by mikhail-vl** [comment]
We decided not to introduce additional logic for nested object at this point and update documentation following your workaround: https://volkovlabs.io/plugins/business-forms/data-flow/#use-nested-objects-in-payload.

  Interpolation and Serialization are use case specific and should be controlled by form developers.
