### ISSUE TITLE
Unable to enter multi-digit numbers in "Select with custom options" form element

### ISSUE THREAD

**Issue by octal-ip** [VolkovLabs/business-forms#551]
When creating a form element that has a "Select with custom items" type, multiple digit numbers starting with a digit that is already used in another value cannot be entered.

For example, if I have an option with the value of 1, I cannot have other options with the value of 10, 11, 12, etc as an "Option with the same value exists" error message appears as soon as the number 1 is entered. Evaluating whether a number is already in use should occur when clicking away from the value field rather than at every key stroke.

![image](https://github.com/user-attachments/assets/624b91ed-037d-4324-8754-9ab99a3c1fa3)

**Comment by mikhail-vl** [comment]
@octal-ip Thank you for opening the issue. We reproduced the issue and will update in the upcoming release.
