### ISSUE TITLE
how to stop grafana from hitting the server if server is not working

### ISSUE THREAD

**Issue by ashishagarwal7** [VolkovLabs/business-forms#555]
when the server side is not working, Grafana is still hitting the server. how to stop grafana from syncing the server every min.

<img width="814" alt="image" src="https://github.com/user-attachments/assets/15b86031-17cd-4da3-b24b-7b90af4af4ae">
 
Also initial Request(Synchronize with data) is disabled

<img width="362" alt="image" src="https://github.com/user-attachments/assets/7b42acf4-2994-4588-8981-0fcdec265047">

**Comment by mikhail-vl** [comment]
@ashishagarwal7 You can use custom code as described in documentation.
