### ISSUE TITLE
Add table as a new type of form elements with buttons for each line

### ISSUE THREAD

**Issue by vsile** [VolkovLabs/business-forms#556]
I have a simple table with multiple lines.
![Screenshot_20241120_173850](https://github.com/user-attachments/assets/db189eb2-7dcf-4b6e-8d41-d89313f10913)

It would be perfect to create a form with "Table" type and buttons for each line and assign it to URL
http://myawesomesite.com/payments/delete?id=$_id

![Screenshot_20241120_171517](https://github.com/user-attachments/assets/4f3de3d6-da31-41b7-975c-08e85c788374)

**Comment by mikhail-vl** [comment]
@vsile Have you seen our new panel Business Table https://volkovlabs.io/plugins/business-table/?

  Adding and deleting rows will be implemented in https://github.com/VolkovLabs/business-table/issues/98 in the next release.
