### ISSUE TITLE
Verify new lines in text area for Windows users

### ISSUE THREAD

**Issue by mikhail-vl** [VolkovLabs/business-forms#557]
Similar to https://github.com/VolkovLabs/business-table/pull/176

**Comment by KaungMAung** [comment]
I can confirm that both version 4.8 and 4.9 got similar issue.

**Comment by mikhail-vl** [comment]
@KaungMAung Do you use Windows to test? We reproduced the issue and will update Code Editor to convert `\r\n` to `\n` similar to Linux, MacOS in the upcoming version.

**Comment by KaungMAung** [comment]
> @KaungMAung Do you use Windows to test? We reproduced the issue and will update Code Editor to convert `\r\n` to `\n` similar to Linux, MacOS in the upcoming version.

Hi @mikhail-vl , we are running on windows server.

**Comment by mikhail-vl** [comment]
@KaungMAung We are updating the Code Editor component and will include in the Business Forms and Business Table panels in the upcoming releases.
