### ISSUE TITLE
Old Data remain at Form After submit, Need to be clear

### ISSUE THREAD

**Issue by KaungMAung** [VolkovLabs/business-forms#559]
Form Version : 4.9
Grafana version : 11.2

After submited form, old data remain in display field, But You actually cannot use beause when you submit again without changing data of those fields, those fields are blank (or NULL) eventhough you can see values visiually . So, I think we better clear of those data fields after submitted. (in this use case, Form is new entry form, not assigning any data from inital request)

Thanks and Rgds,
K

**Comment by mikhail-vl** [comment]
@KaungMAung Depending on your use case you can refresh dashboard using `refresh()` function or do options change to clearing out state and trigger panel refresh.
