### ISSUE TITLE
Update confirmation window code

### ISSUE THREAD

**Issue by rthill** [VolkovLabs/business-forms#565]
When a user attempts to update settings, I need to manually inject alerts into the update request payload to prevent them from submitting mutually exclusive options. This process ensures that invalid combinations are not sent to the backend,

The ability to add custom logic to the update confirmation window would allow for dynamic workflows, enabling additional checks and validations before finalizing updates. It would shift validation closer to the user interface, reducing backend overhead and providing a better user experience.

**Comment by vitPinchuk** [comment]
@rthill Thank you for your question

You can implement this already in the current version. 

`Change Value` editor allows you to implement displaying alert or info messages. 

You can check if the value of a form element has changed and prevent it from changing if it does not match your requirements 

Additionally, You can also implement the logic at the payload preparation level, and exclude unnecessary values. 

Please, also consider a possible visual variant of using the panel. You can set 2 sections. In the first section you can place items and set there the values received at the initial req. And you can use the second section and its elements to manipulate and send data.

Let me know if any of the suggestions were helpful to you
